version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: 3.4.2
    ports:
      - "3000:3000"  # 将容器内的80端口映射为本地3000端口访问
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: dummy_key_for_local
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
